feat: add is_first/is_last properties + expose buffers
willothy/nvim-cokeline pull request #54
Opened 2022-03-18 00:08 UTC by cwqt

Adds `is_first` & `is_last` properties onto the `buffer` parameter. Useful for knowing if a tab is the first or last in the set of buffers.

Also exposes all the buffers as an argument, e.g.

```lua
{
  text: function(buffer, buffers) 
    if(buffer.is_first) return "first"
    if(buffer.is_last) return "last"
    return buffer.index .. "/" .. #buffers
  end
}
```

I've been using it in my config for a bit now https://gitlab.com/cxss/dotfiles/-/blob/main/nvim/lua/core/bufferline.lua#L52

2022-03-18 18:53 UTC, noib3 requested changes

2022-03-18 18:53 UTC, noib3 commented on lua/cokeline/buffers.lua
> +    buffer.is_last = i == #_G.cokeline.visible_buffers
There's no need to set these in every iteration of the loop, just set them once before the loop
```lua
_G.cokeline.visible_buffers[1].is_first = true
_G.cokeline.visible_buffers[#_G.cokeline.visible_buffers].is_first = true
for ...
```

2022-03-18 18:53 UTC, noib3 commented on lua/cokeline/components.lua
> +      or (type(field) == "function" and field(buffer, _G.cokeline.valid_buffers))
What's the benefit of exposing all the valid buffers to the users?

2023-03-28 00:33 UTC, willothy commented
Feel free to ping me if this is still needed, but since it doesn't seem necessary to expose all of the buffers and we already have #69 merged from a while ago, I'm going to close this.

2023-03-28 00:33 UTC, closed without merging